#!/bin/bash -e

# PURPOSE: Change irods env and iget remote file
#
# EXAMPLE:
#  get_other_host.sh irods_file local_file
#
# AUTHORS: S. Pothier

cmd=`basename $0`
usage="USAGE: $cmd irods_fname local_fname
"

if [ $# -lt 2 ]; then
	echo >&2 "$usage"
	exit 2
fi

irods_fname=$1
local_fname=$2


##############################################################################

PATH=~/sandbox/irods3.3.1/iRODS/clients/icommands/bin:$PATH
which iinit

mv ~/.irods/.irodsEnv ~/.irods/origIrodsEnv
cat > ~/.irods/archIrodsEnv <<EOF
irodsHost db5.sdm.noao.edu
irodsPort 1247
irodsUserName cache
irodsZone noao-tuc-z1
irodsDefResource tadaResc
irodsHome /noao-tuc-z1/home/cache
irodsCwd /noao-tuc-z1/home/cache
EOF
#! export irodsLogLevel=9

cp ~/.irods/archIrodsEnv ~/.irods/.irodsEnv
#!read -p "iRODS password for cache user? "
#!iinit $REPLY
iinit cacheMonet
ienv

iget -f -K ${irods_fname} ${local_fname}

echo "Successfully iget ${irods_fname} to ${local_fname}"
