#!/bin/bash -e

# PURPOSE: iput local file using previously installed .irodsEnv
#
# EXAMPLE: 
#
# AUTHORS: S. Pothier

cmd=`basename $0`
usage="USAGE: $cmd local_fname irods_fname
"

if [ $# -lt 2 ]; then
	echo >&2 "$usage"
	exit 2
fi

local_fname=$1
irods_fname=$2

##############################################################################

PATH=/sandbox/irods3.3.1/iRODS/clients/icommands/bin:$PATH
imkdir -p `dirname ${irods_fname}`
#! chmod 0664 ${local_fname}
iput -f -K ${local_fname} ${irods_fname}

echo "Successfully put ${local_fname} to ${irods_fname}"
