#!/bin/bash
# PURPOSE: Initiate submit of fits file to archive
#   Sets options for use by tada at valley to add to fits header.
#
# EXAMPLE: 
#
# AUTHORS: S. Pothier

#!cmd=`basename $0`
#!dir=`dirname $0`

#Absolute path to this script
SCRIPT=$(readlink -f $0)
#Absolute path this script is in
SCRIPTPATH=$(dirname $SCRIPT)


usage="USAGE: $cmd [options] fitsFile ...
"

MINARGS=1
if [ $# -lt $MINARGS ]; then
    echo >&2 "ERROR: Wrong number of arguments.  Got $#, expected $MINARGS"
    echo >&2 "$usage"
    exit 2
fi


##############################################################################

# Mix personalities of observatory, instrument
source ${SCRIPTPATH}/KPNO.personality
source ${SCRIPTPATH}/BOK.personality

opts=""
today=`date '+%Y-%m-%d'`

#!read -p "What is your Proposal ID? (File will not be archived without valid ID) " PROPID
opts="$opts -o _OBSERVAT=${OBSERVAT} -o _DTTELESC=${DTTELESC}"
opts="$opts -o _PROPID=${PROPID} -o _INSTRUME=${INSTRUME} -o _DTTITLE=${DTTITLE}"
opts="$opts -o _DTCALDAT=$today"


for filename; do
    #! echo "EXECUTE: lp -d astro $opts ${filename}"
    lp -d astro $opts ${filename}
done
