#!/bin/bash -e
#
#  FOR DIAGNOSTICS ONLY
#
# PURPOSE: Change irods env and irsync remote files
#
# EXAMPLE:
#
# AUTHORS: S. Pothier

cmd=`basename $0`
usage="USAGE: $cmd irods_path local_path
"

if [ $# -lt 2 ]; then
	echo >&2 "$usage"
	exit 2
fi

irods_path=$1
local_path=$2


##############################################################################

PATH=/sandbox/irods3.3.1/iRODS/clients/icommands/bin:$PATH

mv ~/.irods/.irodsEnv ~/.irods/origIrodsEnv
cat > ~/.irods/archIrodsEnv <<EOF
irodsHost db5.sdm.noao.edu
irodsPort 1247
irodsUserName cache
irodsZone noao-tuc-z1
irodsDefResource tadaResc
irodsHome /noao-tuc-z1/home/cache
irodsCwd /noao-tuc-z1/home/cache
EOF
#! export irodsLogLevel=9

cp ~/.irods/archIrodsEnv ~/.irods/.irodsEnv
read -p "iRODS password for cache user? "
iinit $REPLY

ienv

echo "Files to sync:"
irsync -l -r -s i:${irods_path} ${local_path} | awk '{print $1}'

#! iquest “%s/%s” “select COLL_NAME, DATA_NAME where DATA_OWNER_ZONE =‘my_zone’"

#!echo "Begin sync:"
#!irsync -v -r -s i:${irods_path} ${local_path}


echo "DONE!"
