#!/bin/bash -e
# PURPOSE: Use on dome to send file on its way to archive
#
# EXAMPLE:
#  fromdome -v 1 -s bok /data/bok/bokrm.20140425.0119.fits
#
# AUTHORS: S.Pothier

cmd=`basename $0`
dir=`dirname $0`

#Absolute path to this script
SCRIPT=$(readlink -f $0)
#Absolute path this script is in
SCRIPTPATH=$(dirname $SCRIPT)

SYSTEM=kosmos

usage="USAGE: $cmd [options] fitsFile ...
OPTIONS:
  -s <system>::    Name of system that produced the file (default='$SYSTEM')
  -v <verbosity>:: higher number for more output (default=0)

"

VERBOSE=0
while getopts "hs:v:" opt; do
    #!echo "opt=<$opt>"
    case $opt in
	h)
            echo "$usage"
            exit 1
            ;;
        v)
            VERBOSE=$OPTARG
            ;;
        s)
	    # What system is this for?
            SYSTEM=$OPTARG 
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;

    esac
done
#echo "OPTIND=$OPTIND"
for (( x=1; x<$OPTIND; x++ )); do shift; done


RAC=1 # Required Argument Count
if [ $# -lt $RAC ]; then
    echo "Not enough non-option arguments. Expect at least $RAC."
    echo >&2 "$usage"
    exit 2
fi


#! echo "VERBOSE=$VERBOSE"
#! echo "Remaining arguments:"
#! for arg do echo '--> '"\`$arg'" ; done

##############################################################################

if [ "$VERBOSE" -gt 0 ]; then
    echo "SYSTEM=$SYSTEM"
fi

if [ "bok" = "$SYSTEM" ]; then
    options="-o _INSTRUME=90Prime -o _OBSERVAT=Steward"
    options="${options} -o _PROPID=2014B-0bok" 
elif [ "kosmos" = "$SYSTEM" ]; then
    options=""
else
    echo >&2 "$usage"
    echo >&2 "ERROR: Unexpected '-s' value ($SYSTEM)"
    exit 3
fi

for fname; do
    if [ "$VERBOSE" -gt 0 ]; then
	echo "lpr -P astro ${options} ${fname}"
    fi
    lpr -P astro ${options} ${fname}
done


##############################################################################
# Local Variables:
# fill-column:75
# mode:sh
# End:

