#!/bin/bash -e

# PURPOSE: Change irods env and iget remote file
#
# EXAMPLE:
#  get_other_host.sh irods_file local_file
#
# AUTHORS: S. Pothier

cmd=`basename $0`
usage="USAGE: $cmd irods_fname local_fname
"

if [ $# -lt 2 ]; then
	echo >&2 "$usage"
	exit 2
fi

irods_fname=$1
local_fname=$2


##############################################################################


iget -f -K ${irods_fname} ${local_fname}

echo "Successfully iget ${irods_fname} to ${local_fname}"
